# Adapted from [1]:
# [1]: https://github.com/kachick/dotfiles/blob/main/.github/workflows/ci-home.yml
name: Nix Flake Check
on: 
  push:
    paths:
      - '.github/workflows/check.yml'
      - 'modules/**/*'
      - 'pkgs/**/*'
      - '*.nix'
      - 'flake.lock'

jobs:
  check:
    uses: Joaqim/dotfiles/.github/workflows/reusable-nix-flake-check.yml@main
