# Initially taken from [1]:
# [1]: https://github.com/tgirlcloud/pkgs/blob/main/.github/workflows/docs.yml
name: Build and deploy docs

on:
  workflow_dispatch:
  push:
    paths:
      - "modules/**/*"
      - "docs/**/*"
      - ".github/workflows/docs.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix and Configure Attic Binary Cache
        uses: ./.github/actions/install-nix-with-attic-cache  
        with:
          attic-endpoint: ${{ vars.ATTIC_ENDPOINT }}
          attic-cache-name: jqpkgs
          extra-nix-config: |
            substituters = https://nix-community.cachix.org?priority=41 https://numtide.cachix.org?priority=42 https://cache.nixos.org/
            trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= numtide.cachix.org-1:2ps1kLBUWjxIneOy1Ik6cQjb41X0iXVXeHigGmycPPE= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            fallback = true
            http-connections = 128
            max-substitution-jobs = 128
            download-buffer-size = 524288000
            extra-substituters = ${{ vars.MY_BINARY_CACHE }}?priority=43
            extra-trusted-public-keys = ${{ vars.MY_BINARY_CACHE_PUBLIC_KEY }}
          
          tailscale-oauth-client-id: ${{ vars.TS_OAUTH_CLIENT_ID }}
          
          # Secrets
          tailscale-oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          attic-token: ${{ secrets.ATTIC_TOKEN }}
          github-token: ${{ secrets.GH_READ_TOKEN }}

      - name: Build docs
        run: nix build -L ./docs#jqpkgs-docs

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: result

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
