# Initially taken from [1]:
# [1]: https://github.com/tgirlcloud/pkgs/blob/main/.github/workflows/docs.yml
name: Deploy docs

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/docs.yml"
      - "modules/**/*"
      - "docs/**/*"


jobs:
  deploy-docs:
    if: (github.triggering_actor != 'dependabot[bot]')
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v19
        with:
          logger: pretty
          diagnostic-endpoint: ""

      - name: Build docs
        run: nix build -L ./docs#jqpkgs-docs

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: result

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
