name: 'Setup Attic Cache via Tailscale'
description: 'Connect to Tailscale network and configure Nix with Attic binary cache'

inputs:
  # Attic configuration
  attic-endpoint:
    description: 'Attic endpoint URL'
    required: true
  
  attic-cache-name:
    description: 'Attic cache name'
    required: true
    default: 'cache'

  attic-skip-push:
    description: 'Skip pushing new derivations to Attic at exit'
    required: false
    default: 'false'

  # Secrets
  tailscale-oauth-client-id:
    description: 'Tailscale OAuth client ID'
    required: true
  
  tailscale-oauth-secret:
    description: 'Tailscale OAuth client secret'
    required: true
  
  attic-token:
    description: 'Attic token'
    required: true
  
  # Optional configuration
  github-token:
    description: 'GitHub token for Nix installer'
    required: false
    default: ${{ github.token }}
  
  extra-nix-config:
    description: 'Additional Nix configuration'
    required: false
    default: ''
  
  attic-inputs-from:
    description: 'Path to attic inputs (flake.nix location)'
    required: false
    default: './'

runs:
  using: 'composite'
  steps:
    - name: Connect to Tailscale (GitHub-hosted)
      if: runner.environment == 'github-hosted'
      uses: tailscale/github-action@v3.2.3
      with:
        use-cache: 'true'
        oauth-client-id: ${{inputs.tailscale-oauth-client-id }}
        oauth-secret: ${{ inputs.tailscale-oauth-secret  }}
        tags: tag:ci

    - name: Connect to Tailscale (Self-hosted)
      if: runner.environment != 'github-hosted'
      uses: Pikachews/tailscale-action@main
      with:
        oauth-client-id: ${{ inputs.tailscale-oauth-client-id }}
        oauth-secret: ${{ inputs.tailscale-oauth-secret }}
        tags: tag:ci

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v18
      with:
        github-token: ${{ env.GH_READ_TOKEN }}
        logger: pretty
        diagnostic-endpoint: ""
        extra-conf: ${{ inputs.extra-nix-config }}
      env:
        GH_READ_TOKEN: ${{ inputs.github-token }}

    - name: Setup Attic
      uses: ryanccn/attic-action@v0.3.2
      with:
        inputs-from: ${{ inputs.attic-inputs-from }}
        endpoint: ${{ inputs.attic-endpoint }}
        cache: ${{ inputs.attic-cache-name }}
        token: ${{ inputs.attic-token }}
        skip-push: ${{ inputs.attic-skip-push }}
